name: Django CI

on:
  push:
    branches: [ w ]
  pull_request:
    branches: [ comsem-demo ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: zergling
          MYSQL_DATABASE: CommunicationSeminarDjango
        ports: ['3306:3306']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env:
          DB_PASSWORD: zergling
    - name: Run Tests
      run: |
        python manage.py test
      env:
          DB_PASSWORD: zergling
